@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/CatalystX-TraitFor-Dispatcher-ExactMatch/project>
	deps:runtime-requirement         [ deps:on "Moose::Role"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Catalyst::Runtime 5.80"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "CatalystX::RoleApplicator"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

