# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/CatalystX-TraitFor-Dispatcher-ExactMatch/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires "MooseX::Declare" , "Catalyst::Runtime 5.80" , "CatalystX::RoleApplicator" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/CatalystX/TraitFor/Dispatcher/ExactMatch.pm" .

